appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat

# 실제 SQL 출력
customLogMessageFormat=%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)

# 로그 제외
excludecategories=info,debug,result,commit,resultset,batch